import { Combination, Option, Row } from "./types";
export declare class OptionHandler {
    private readonly options;
    private possibleCombinations;
    private readonly optionKeys;
    constructor(options: Option);
    generateAllPossibleCombinations(): Combination[];
    groupCombinations(combinations: Combination[]): Row[];
    private splitIncompleteAllRows;
    private splitIncompleteRow;
    private hasIncompleteAllRows;
    private hasIncompleteAll;
    private tryToMergeRowsWithAll;
    private countTotalAllOption;
    private removeFalseCombinations;
    private isValidCombination;
    private removeRowsWithEmptyOptionItem;
    private mergeRows;
    private balanceRowsRelevance;
    private getRowWeight;
    private convertCombinationsToRow;
    private isCombinationInRows;
    private isCombinationInRow;
    private convertRowToCombinations;
    private removeFalseAllElements;
    private validateAndRemoveFalseAll;
    private rowHasAll;
    private convertOptionRowsToRows;
    private removeDuplicatedFindAll;
    private isRowsIdentical;
    private hasEqualAll;
    private mergeOptionCombinations;
    private mergeOptionItemCombinations;
    private mergeCombinations;
    private compareCombinations;
    private findSelectedOptionInCombination;
    private generateCombinations;
    private compareCombination;
}
